baseurl = "http://netzap.in/"
languageCode = "en-us"
title = "netzap digital"
theme = "hugo-creative-theme"
googleAnalytics = "UA-39923282-1"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "Your name"
  description = "Your description"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "[N] netzap digital"

    [params.navigation.links]
      about     = "About"
      services  = "Services"
      portfolio = "Products"
      method = "Methodology"
      contact   = "Contact"
      location = "Location"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Welcome to the Web 3.0"
    subtitle1   = "Make the web work for you. Let us help you impact "
    cue = "your business"
    subtitle2 = " with low foot print, progressive web applications, today!"
    buttonText = "Find out more"


  # About section
  [params.about]
    headline    = "We've got what it takes!"
    description1 = "Today the techology scales are more even than ever before; Modern Technologies are now easy to call upon and easier still to cause an impact to your business. In your IT [strategy](https://research.gartner.com/definition-whatis-bimodal), a team like our plays the role of the exploratory teams with quick impact best."
    cue = "netzap digital"
    description2 = "provdies a selection of services & solutions based on [Salesforce.com](https://salesforce.com), [Heroku](https://heroku.com), [Ruby on Rails](http://rubyonrails.org)"
    buttonText  = "Contact Us Today!"


  # Service section
  [params.services]
    headline = "We Understand Technology"

        [[params.services.list]]
            icon = "fa-cloud "
            title = "Salesforce.com"
            description = "We have extensive experience in the Salesforce eco system, with particular focus on Sales Cloud, Service Cloud, Community Cloud and Force.com"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Ruby on Rails"
            description = "Our tool of choice for custom web applications is Ruby on Rails (RoR). RoR is backed by robust community and extentions. We prefer to deploy on Heroku from the Salesforce.com ecosystem"


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
  #[params.aside]
    #headline = "Get the Creative Theme for Hugo"

    #[params.aside.button]
      #text = "Download now"
      #link = "//github.com/digitalcraftsman/hugo-creative-theme"

    # Method section
  [params.method]
    headline    = "How do we do it?"
      [[params.method.list]]
        icon = "fa-compress"
        title = "Micro Teams"
        description = "We have empowered small teams focusing on business problems. We have found smaller teams to be effective and seen that there is increased ownership, taking the project to completion"

      [[params.method.list]]
        icon = "fa-cogs"
        title = "Agile"
        description = "We belive in short sprints to allow for frequent demo and feedback"

      [[params.method.list]]
            icon = "fa-paper-plane"
            title = "Ready to Ship"
            description = "We choose managed clouds to reduce the footprint of manitanence teams"

        [[params.method.list]]
            icon = "fa-asterisk"
            title = "Limited Portfolio"
            description = "We have a conciously limited client base and technology base. This allows us to be deeply involved in the clients and the technology"


  # Contact section
  [params.contact]
    headline = "Let's Get In Touch!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "+91 988 642 5436"
    email = "prasanthabr@netzap.in"
    timezone = "We operate in the Indian Standard Time (GMT+5:30) allowing us overlaps over EMEA and ASPAC"

  # Google Maps section
  [params.location]
     latitude  = "13.0246434"
     longitude = "77.6006631"
     maps_api_key = "AIzaSyDX6emJTwvfFv1H4BNZbNblLbccgYjPjQU"
